server:
  port: 8090
  tomcat:
    threads:
      max: 500
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/middle_wire?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 10
      max-wait: 60000
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 100
      validation-query: select 1
  redis:
    database: 0
    #Redis服务器地址
    host: localhost
    lettuce:
      pool:
        max-active: 100
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池中的最小空闲连接
        min-idle: 0
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
    #连接超时时间（毫秒）
    timeout: 5000

mybatis:
  #po对象的包
  type-aliases-package: cn.edu.xmu.level46db.model.po
  #mapper.xml所在的位置
  mapper-locations: classpath*:cn.edu.xmu.level46db.mapper/*.xml



# 线程池配置
async-pool:
  # 消费kafka使用的线程池
  rush-cet:
    corePoolSize: 50
    maxPoolSize: 50
    keepAliveSeconds: 120
    queueCapacity: 9999999
  insert-order:
    corePoolSize: 50
    maxPoolSize: 50
    keepAliveSeconds: 120
    queueCapacity: 9999999
