package cn.edu.xmu.level46db.mapper;

import cn.edu.xmu.level46db.model.po.CETOrderInfoPo;
import cn.edu.xmu.level46db.model.po.CETOrderInfoPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CETOrderInfoPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cet_order_info
     *
     * @mbg.generated
     */
    int deleteByExample(CETOrderInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cet_order_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cet_order_info
     *
     * @mbg.generated
     */
    int insert(CETOrderInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cet_order_info
     *
     * @mbg.generated
     */
    int insertSelective(CETOrderInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cet_order_info
     *
     * @mbg.generated
     */
    List<CETOrderInfoPo> selectByExample(CETOrderInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cet_order_info
     *
     * @mbg.generated
     */
    CETOrderInfoPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cet_order_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CETOrderInfoPo record, @Param("example") CETOrderInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cet_order_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CETOrderInfoPo record, @Param("example") CETOrderInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cet_order_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CETOrderInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cet_order_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CETOrderInfoPo record);
}