package cn.edu.xmu.level46db.mapper;

import cn.edu.xmu.level46db.model.po.CETPo;
import cn.edu.xmu.level46db.model.po.CETPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CETPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cet_table
     *
     * @mbg.generated
     */
    int deleteByExample(CETPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cet_table
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cet_table
     *
     * @mbg.generated
     */
    int insert(CETPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cet_table
     *
     * @mbg.generated
     */
    int insertSelective(CETPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cet_table
     *
     * @mbg.generated
     */
    List<CETPo> selectByExample(CETPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cet_table
     *
     * @mbg.generated
     */
    CETPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cet_table
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CETPo record, @Param("example") CETPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cet_table
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CETPo record, @Param("example") CETPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cet_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CETPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cet_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CETPo record);
}