apiVersion: apps/v1
kind: Deployment
metadata:
  # 部署名字
  name: cet-homework
spec:
  replicas: 2
  # 用来查找关联的 Pod，所有标签都匹配才行
  selector:
    matchLabels:
      app: cet-homework
  # 定义 Pod 相关数据
  template:
    metadata:
      labels:
        app: cet-homework
    spec:
      # 定义容器，可以多个
      containers:
      - name: cet-homework # 容器名字
        image: cet:01 # 镜像

---


apiVersion: v1
kind: Service
metadata:
  name: cet-homework
spec:
  selector:
    app: cet-homework
  type: ClusterIP
  ports:
    - port: 8090        # 本 Service 的端口
      targetPort: 8090  # 容器端口