version: "3"

services:
  cet46:
    image: cet46:1.0
    build: .
    container_name: cet46
    restart: always
    ports:
      - "8090:8090"
    depends_on:
      - redis
      - mysql
      - rmqbroker
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - "./redis/redis.conf:/etc/redis/redis.conf"
    command: ["redis-server","/etc/redis/redis.conf"]
    expose:
      - 6379
  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "middle_wire"
    ports:
      - "3306:3306"
    expose:
      - 3306
      - 33060
    volumes:
      - "./mysql/db:/var/lib/mysql"
      - "./mysql/conf/my.cnf:/etc/my.cnf"
      - "./mysql/init:/docker-entrypoint-initdb.d/"
  rmqnamesrv:
    image: foxiswho/rocketmq:4.8.0
    container_name: rmqnamesrv
    restart: always
    ports:
      - 9876:9876
    volumes:
      - "./rmqs/logs:/home/rocketmq/logs"
      - "./rmqs/store:/home/rocketmq/store"
    environment:
      JAVA_OPT_EXT: "-Duser.home=/home/rocketmq -Xms256M -Xmx256M -Xmn128m"
    command: ["sh","mqnamesrv"]
  rmqbroker:
    image: foxiswho/rocketmq:4.8.0
    container_name: rmqbroker
    restart: always
    ports:
      - 10909:10909
      - 10911:10911
    volumes:
      - "./rmq/logs:/home/rocketmq/logs"
      - "./rmq/store:/home/rocketmq/store"
      - "./rmq/brokerconf/broker.conf:/etc/rocketmq/broker.conf"
    environment:
      JAVA_OPT_EXT: "-Duser.home=/home/rocketmq -Xms256M -Xmx256M -Xmn128m"
    command: ["sh","mqbroker","-c","/etc/rocketmq/broker.conf","-n","rmqnamesrv:9876","autoCreateTopicEnable=true"]
    depends_on:
      - rmqnamesrv
  rmqconsole:
    image: styletang/rocketmq-console-ng
    container_name: rmqconsole
    restart: always
    ports:
      - 8180:8080
    environment:
      JAVA_OPTS: "-Drocketmq.namesrv.addr=rmqnamesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    depends_on:
      - rmqnamesrv
