package cn.edu.xmu.level46db.model.po;

import java.time.LocalDateTime;

public class CETOrderInfoPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cet_order_info.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cet_order_info.cet_id
     *
     * @mbg.generated
     */
    private Long cetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cet_order_info.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cet_order_info.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cet_order_info.id
     *
     * @return the value of cet_order_info.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cet_order_info.id
     *
     * @param id the value for cet_order_info.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cet_order_info.cet_id
     *
     * @return the value of cet_order_info.cet_id
     *
     * @mbg.generated
     */
    public Long getCetId() {
        return cetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cet_order_info.cet_id
     *
     * @param cetId the value for cet_order_info.cet_id
     *
     * @mbg.generated
     */
    public void setCetId(Long cetId) {
        this.cetId = cetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cet_order_info.create_time
     *
     * @return the value of cet_order_info.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cet_order_info.create_time
     *
     * @param createTime the value for cet_order_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cet_order_info.user_id
     *
     * @return the value of cet_order_info.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cet_order_info.user_id
     *
     * @param userId the value for cet_order_info.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}