package cn.edu.xmu.level46db.model.po;

import java.time.LocalDate;

public class CETPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cet_table.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cet_table.type
     *
     * @mbg.generated
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cet_table.year
     *
     * @mbg.generated
     */
    private Integer year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cet_table.month
     *
     * @mbg.generated
     */
    private Integer month;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cet_table.begin_date
     *
     * @mbg.generated
     */
    private LocalDate beginDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cet_table.end_date
     *
     * @mbg.generated
     */
    private LocalDate endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cet_table.stock
     *
     * @mbg.generated
     */
    private Long stock;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cet_table.id
     *
     * @return the value of cet_table.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cet_table.id
     *
     * @param id the value for cet_table.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cet_table.type
     *
     * @return the value of cet_table.type
     *
     * @mbg.generated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cet_table.type
     *
     * @param type the value for cet_table.type
     *
     * @mbg.generated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cet_table.year
     *
     * @return the value of cet_table.year
     *
     * @mbg.generated
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cet_table.year
     *
     * @param year the value for cet_table.year
     *
     * @mbg.generated
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cet_table.month
     *
     * @return the value of cet_table.month
     *
     * @mbg.generated
     */
    public Integer getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cet_table.month
     *
     * @param month the value for cet_table.month
     *
     * @mbg.generated
     */
    public void setMonth(Integer month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cet_table.begin_date
     *
     * @return the value of cet_table.begin_date
     *
     * @mbg.generated
     */
    public LocalDate getBeginDate() {
        return beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cet_table.begin_date
     *
     * @param beginDate the value for cet_table.begin_date
     *
     * @mbg.generated
     */
    public void setBeginDate(LocalDate beginDate) {
        this.beginDate = beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cet_table.end_date
     *
     * @return the value of cet_table.end_date
     *
     * @mbg.generated
     */
    public LocalDate getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cet_table.end_date
     *
     * @param endDate the value for cet_table.end_date
     *
     * @mbg.generated
     */
    public void setEndDate(LocalDate endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cet_table.stock
     *
     * @return the value of cet_table.stock
     *
     * @mbg.generated
     */
    public Long getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cet_table.stock
     *
     * @param stock the value for cet_table.stock
     *
     * @mbg.generated
     */
    public void setStock(Long stock) {
        this.stock = stock;
    }
}